name: rama_poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  provider: ^6.1.5
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  auto_route: ^10.0.1
  dartz: ^0.10.1
  shimmer: ^3.0.0
  freezed_annotation: ^3.0.0
  hive_ce: ^2.11.2
  hive_ce_flutter: ^2.3.1
  flutter_conditional: ^2.1.0+2
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  freezed: ^3.0.6
  hive_ce_generator: ^1.9.1
  injectable_generator: ^2.7.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/svg/elements/
    - assets/svg/icons/
    - assets/images/ 
    - assets/images/dummies/

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 100
  integrations:
    image: true
    flutter_svg: true
    lottie: true