name: rama_poke_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  provider: ^6.1.5
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # hive_generator: ^2.0.1
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/svg/elements/
    - assets/svg/icons/

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 100
  integrations:
    image: true
    flutter_svg: true
    lottie: true